---
title: "P300 and MCI"
author: "KYP"
date: "2016년 10월 6일"
output: html_document
---

```{r read data, echo=FALSE, message=FALSE, warning=FALSE}
lapply(c("magrittr", "dplyr", "ggplot2", "gridExtra"), require, character.only = T)


setwd("C:/Users/KYP/Dropbox/RBook/201610_P300_MCI/data")
db <- read.csv("P300_MCI.csv", header = T, stringsAsFactors = F)
# db <- read_spss("P300_SNSB_MCI.sav")
setwd("C:/Users/KYP/Dropbox/RBook/201610_P300_MCI/R")

names(db)[1] <- c("No")
# names(db)
# str(db)
# nrow(db)
# summary(db$dis)

db1 <- filter(db, dis == 0 | dis == 2, age > 50, !is.na(p3_BL), depression == 0)

# db1 %>% filter(dis == 0) %>% nrow()
# db1 %>% filter(dis == 2) %>% nrow()

```

## Baseline data

Number of control:  `r db1 %>% filter(dis == 0) %>% nrow()`

Number of MCI: `r db1 %>% filter(dis == 2) %>% nrow()`

## Normality testing
```{r normality, echo=T}

# names(db1)

hist(db1$p3_BL)
# hist(db1$P3_FU)

shapiro.test(db1$p3_BL)
shapiro.test(db1$P3_FU)

```


## Table 1
```{r table 1}

db1 %>% group_by(dis) %>% summarise(mean(age), sd(age), mean(p3_BL), sd(p3_BL))

# correlation: Pearson's r
# db1 %>% group_by(dis) %>% summarise(cor(age, p3_BL))
db1 %>% filter(dis == 0) %>% with(cor.test(age, p3_BL, method = "p"))
db1 %>% filter(dis == 2) %>% with(cor.test(age, p3_BL, method = "p"))


# # correlation: Spearman's rho
# db1 %>% filter(dis == 0) %>% with(cor.test(age, p3_BL, method = "s"))
# db1 %>% filter(dis == 2) %>% with(cor.test(age, p3_BL, method = "s"))

```

```{r multivariable}
# names(db1)

lm(p3_BL ~ factor(dis) + age, data = db1) %>% summary

bartlett.test(db1$p3_BL ~ factor(db1$dis))
t.test(db1$p3_BL ~ factor(db1$dis), var.equal=T)

```


## Graph
```{r graph}

p0 <- db1 %>% filter(dis == 0) %>%
  ggplot(aes(age, p3_BL)) + geom_point() + geom_smooth(method = "lm") +
  scale_x_continuous("Age", breaks = c(60, 70, 80)) +
  scale_y_continuous("P300 Latency") +
  theme_bw() +
  theme(#axis.line = element_line(size = 0.5, colour = "black"),
    text=element_text(size=10),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) +
  ggtitle("Control") +
  annotate(geom = "text", label = "R = 0.62, p < 0.01", x=57, y=390, size=3)

p2 <- db1 %>% filter(dis == 2) %>%
  ggplot(aes(age, p3_BL)) + geom_point() + geom_smooth(method = "lm") +
  scale_x_continuous("Age", breaks = c(60, 70, 80, 90)) +
  scale_y_continuous("P300 Latency") +
  theme_bw() +
  theme(#axis.line = element_line(size = 0.5, colour = "black"),
    text=element_text(size=10),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) +
  ggtitle("MCI") +
  annotate(geom="text", label = "R = 0.15, p = 0.45", x=59.5, y=410, size=3)

grid.arrange(p0, p2, nrow = 1, ncol = 2)

```


## f/u data

number of patient with f/u data: `r db1 %>% filter(!is.na(P3_FU)) %>% nrow`

```{r Wilcoxon signed rank}

db_diff <- db1 %>% filter(!is.na(P3_FU))

cbind(mean(db_diff$p3_BL), sd(db_diff$p3_BL))
cbind(mean(db_diff$P3_FU), sd(db_diff$P3_FU))

wilcox.test(db_diff$p3_BL, db_diff$P3_FU, paired = T)

# if paired t test
shapiro.test(db_diff$p3_BL)
shapiro.test(db_diff$P3_FU)

t.test(db_diff$p3_BL, db_diff$P3_FU, paired = T)
```


```{r f/u graph}


db_diff$p3_diff = db_diff$P3_FU - db_diff$p3_BL
db_diff$p3_color = ifelse(db_diff$p3_diff < 0, 1,
                          ifelse(db_diff$p3_diff == 0, 2, 3))

summary(db_diff$p3_diff)


ggplot(db_diff, aes(x = age, y = p3_diff, color = factor(p3_color))) + 
  geom_point() +
  scale_x_continuous("Age") + 
  scale_y_continuous("F/U P300 - Initial P300") +
  scale_color_discrete("P300 difference", limits = c(1, 3), 
                       labels = c(" F/U < Initial", " F/U > Initial")) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 0.5) +
  theme_bw() +
  theme(#axis.line = element_line(size = 0.5, colour = "black"),
    text=element_text(size=10),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank())
# 
# ggplot(db_diff, aes(x = p3_BL, y = P3_FU)) + geom_point() +
#   geom_abline(intercept=0, slope=1)

```


